package com.nemo.simkl.media.models

/**
 * Enum representing a language.
 *
 * @property value The ISO 639-1 code for the language.
 */
enum class Language(val value: String) {
  ENGLISH("en"),
  SPANISH("es"),
  CASTILIAN("es"),
  KOREAN("ko"),
  AFRIKAANS("af"),
  AMHARIC("am"),
  ARABIC("ar"),
  BASQUE("eu"),
  BELARUSIAN("be"),
  BENGALI("bn"),
  BOSNIAN("bs"),
  BULGARIAN("bg"),
  BURMESE("my"),
  CATALAN("ca"),
  VALENCIAN("ca"),
  CHINESE("zh"),
  CANTONESE("cn"),
  CROATIAN("hr"),
  CZECH("cs"),
  DANISH("da"),
  DIVEHI("dv"),
  DHIVEHI("dv"),
  MALDIVIAN("dv"),
  DUTCH("nl"),
  FLEMISH("nl"),
  ESTONIAN("et"),
  FINNISH("fi"),
  FRENCH("fr"),
  GALICIAN("gl"),
  GEORGIAN("ka"),
  GERMAN("de"),
  GREEK("el"),
  MODERN_GREEK("el"),
  HEBREW("he"),
  HINDI("hi"),
  HUNGARIAN("hu"),
  ICELANDIC("is"),
  INDONESIAN("id"),
  IRISH("ga"),
  ITALIAN("it"),
  JAPANESE("ja"),
  LUXEMBOURGISH("lb"),
  LETZEBURGESCH("lb"),
  LITHUANIAN("lt"),
  MACEDONIAN("mk"),
  MALAY("ms"),
  NEPALI("ne"),
  NORWEGIAN_BOKMAL("nb"),
  BOKMAL("nb"),
  NORWEGIAN_NYNORSK("nn"),
  NYNORSK("nn"),
  NORWEGIAN("no"),
  PERSIAN("fa"),
  POLISH("pl"),
  PORTUGUESE("pt"),
  ROMANIAN("ro"),
  MOLDOVIAN("ro"),
  MOLDOVAN("ro"),
  RUSSIAN("ru"),
  NORTHEN_SAMI("se"),
  SAAMI("se"),
  SERBIAN("sr"),
  SINHALA("si"),
  SINHALESE("si"),
  SLOVAK("sk"),
  SLOVENIAN("sl"),
  SWEDISH("sv"),
  TAMIL("ta"),
  TELUGU("te"),
  TAJIK("tg"),
  THAI("th"),
  TAGALOG("tl"),
  TURKISH("tr"),
  TWI("tw"),
  UKRAINIAN("uk"),
  URDU("ur"),
  VIETNAMESE("vi"),
  WELSH("cy"),
  ZHUANG("za"),
  CHUANG("za");

  override fun toString(): String = value

  companion object {
    val map = Language.entries.associateBy { it.value }
    fun fromValue(value: String) = map[value]
  }
}
