package com.nemo.simkl.media.models

/**
 * Enum representing a language.
 *
 * @property lower The ISO 639-1 code for the language in lowercase.
 * @property upper The ISO 639-1 code for the language in uppercase.
 */
enum class Language(val lower: String, val upper: String) {
  ENGLISH("en", "EN"),
  SPANISH("es", "ES"),
  CASTILIAN("es", "ES"),
  KOREAN("ko", "KO"),
  AFRIKAANS("af", "AF"),
  AMHARIC("am", "AM"),
  ARABIC("ar", "AR"),
  BASQUE("eu", "EU"),
  BELARUSIAN("be", "BE"),
  BENGALI("bn", "BN"),
  BOSNIAN("bs", "BS"),
  BULGARIAN("bg", "BG"),
  BURMESE("my", "MY"),
  CATALAN("ca", "CA"),
  VALENCIAN("ca", "CA"),
  CHINESE("zh", "ZH"),
  CANTONESE("cn", "CN"),
  CROATIAN("hr", "HR"),
  CZECH("cs", "CS"),
  DANISH("da", "DA"),
  DIVEHI("dv", "DV"),
  DHIVEHI("dv", "DV"),
  MALDIVIAN("dv", "DV"),
  DUTCH("nl", "NL"),
  FLEMISH("nl", "NL"),
  ESTONIAN("et", "ET"),
  FINNISH("fi", "FI"),
  FRENCH("fr", "FR"),
  GALICIAN("gl", "GL"),
  GEORGIAN("ka", "KA"),
  GERMAN("de", "DE"),
  GREEK("el", "EL"),
  MODERN_GREEK("el", "EL"),
  HEBREW("he", "HE"),
  HINDI("hi", "HI"),
  HUNGARIAN("hu", "HU"),
  ICELANDIC("is", "IS"),
  INDONESIAN("id", "ID"),
  IRISH("ga", "GA"),
  ITALIAN("it", "IT"),
  JAPANESE("ja", "JA"),
  LUXEMBOURGISH("lb", "LB"),
  LETZEBURGESCH("lb", "LB"),
  LITHUANIAN("lt", "LT"),
  MACEDONIAN("mk", "MK"),
  MALAY("ms", "MS"),
  NEPALI("ne", "NE"),
  NORWEGIAN_BOKMAL("nb", "NB"),
  BOKMAL("nb", "NB"),
  NORWEGIAN_NYNORSK("nn", "NN"),
  NYNORSK("nn", "NN"),
  NORWEGIAN("no", "NO"),
  PERSIAN("fa", "FA"),
  POLISH("pl", "PL"),
  PORTUGUESE("pt", "PT"),
  ROMANIAN("ro", "RO"),
  MOLDOVIAN("ro", "RO"),
  MOLDOVAN("ro", "RO"),
  RUSSIAN("ru", "RU"),
  NORTHEN_SAMI("se", "SE"),
  SAAMI("se", "SE"),
  SERBIAN("sr", "SR"),
  SINHALA("si", "SI"),
  SINHALESE("si", "SI"),
  SLOVAK("sk", "SK"),
  SLOVENIAN("sl", "SL"),
  SWEDISH("sv", "SV"),
  TAMIL("ta", "TA"),
  TELUGU("te", "TE"),
  TAJIK("tg", "TG"),
  THAI("th", "TH"),
  TAGALOG("tl", "TL"),
  TURKISH("tr", "TR"),
  TWI("tw", "TW"),
  UKRAINIAN("uk", "UK"),
  URDU("ur", "UR"),
  VIETNAMESE("vi", "VI"),
  WELSH("cy", "CY"),
  ZHUANG("za", "ZA"),
  CHUANG("za", "ZA");

  override fun toString(): String = upper

  companion object {
    val map = Language.entries.associateBy { it.lower }
    fun fromValue(value: String) = map[value.lowercase()]
  }
}
